Improve project generation

diff --git a/{{ cookiecutter.project_slug }}/.github/workflows/frontend.yml b/{{ cookiecutter.project_slug }}/.github/workflows/frontend.yml
--- a/{{ cookiecutter.project_slug }}/.github/workflows/frontend.yml
+++ b/{{ cookiecutter.project_slug }}/.github/workflows/frontend.yml
@@ -8,94 +8,68 @@ on:
   workflow_dispatch:
 
 env:
-  node-version: 16.x
+  IMAGE_NAME_PREFIX: {{ cookiecutter.__docker_image_prefix }}{{ cookiecutter.github_organization }}/{{ cookiecutter.project_slug }}
+  IMAGE_NAME_SUFFIX: frontend
+  NODE_VERSION: {{ cookiecutter.__node_version }}.x
 
 jobs:
 
-  eslint:
+  code-analysis:
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./frontend
     steps:
       - name: Checkout codebase
         uses: actions/checkout@v3
 
-      - name: Use Node.js {{"${{ env.node-version }}"}}
+      - name: Update Global Yarn
+        run: |
+          corepack enable
+          corepack prepare yarn@stable --activate
+
+      - name: Use Node.js {{ "${{ env.node-version }}" }}
         uses: actions/setup-node@v3
         with:
-          node-version: {{"${{ env.node-version }}"}}
+          node-version: {{ "${{ env.NODE_VERSION }}" }}
           cache: 'yarn'
           cache-dependency-path: 'frontend/yarn.lock'
 
-      - name: Install packages
-        run: make install
-
-      - name: Lint
-        run: yarn run lint:ci
-
-  prettier:
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./frontend
-    steps:
-      - name: Checkout codebase
-        uses: actions/checkout@v3
-
-      - name: Run Prettier
+      - name: Prettier
+        id: prettier
         run: npx prettier@2.0.5 --single-quote --check 'src/**/*.{js,jsx,ts,tsx,css,scss}' --config=package.json
 
-
-  i18n:
-    name: i18n sync
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: frontend
-
-    steps:
-      - name: Checkout codebase
-        uses: actions/checkout@v3
-
-      - name: Use Node.js {{"${{ env.node-version }}"}}
-        uses: actions/setup-node@v3
-        with:
-          node-version: {{"${{ env.node-version }}"}}
-          cache: 'yarn'
-          cache-dependency-path: 'frontend/yarn.lock'
-
       - name: Install packages
         run: make install
 
-      - name: Test i18n sync
+      - name: ESLint
+        id: eslint
+        if: {{ "${{ success() || failure() }}" }}
+        run: yarn run lint:ci
+
+      - name: i18n sync
+        id: i18n
+        if: {{ "${{ success() || failure() }}" }}
         run: make i18n-ci
 
-  unit:
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./frontend
-    steps:
-      - name: Checkout codebase
-        uses: actions/checkout@v3
-
-      - name: Use Node.js {{"${{ env.node-version }}"}}
-        uses: actions/setup-node@v3
-        with:
-          node-version: {{"${{ env.node-version }}"}}
-          cache: 'yarn'
-          cache-dependency-path: 'frontend/yarn.lock'
-
-      - name: Install packages
-        run: make install
-
-      - name: Test
+      - name: Unit Tests
+        id: unit
+        if: {{ "${{ success() || failure() }}" }}
         run: make test
+
+      - name: Report
+        if: {{ "${{ success() || failure() }}" }}
+        run: |
+          echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
+          echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
+          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
+          {{ "echo '| Prettier | ${{ steps.prettier.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY" }}
+          {{ "echo '| ESLint | ${{ steps.eslint.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY" }}
+          {{ "echo '| i18n | ${{ steps.i18n.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY" }}
+          {{ "echo '| Unit Tests | ${{ steps.unit.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY " }}
+
 
   release:
     runs-on: ubuntu-latest
-    needs: [eslint, prettier, i18n, unit]
+    needs:
+      - code-analysis
     permissions:
       contents: read
       packages: write
@@ -103,16 +77,16 @@ jobs:
     steps:
 
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Docker meta
         id: meta
-        uses: docker/metadata-action@v4
+        uses: docker/metadata-action@v5
         with:
           images: |
-            {{ cookiecutter.__docker_image_prefix }}{{ cookiecutter.github_organization}}/{{ cookiecutter.project_slug }}-frontend
+            {{ "${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}" }}
           labels: |
-            org.label-schema.docker.cmd=docker run -d -p 3000:3000 {{ cookiecutter.__docker_image_prefix }}{{ cookiecutter.github_organization}}/{{ cookiecutter.project_slug }}-frontend:latest
+            org.label-schema.docker.cmd=docker run -d -p 3000:3000 {{ "${{ env.IMAGE_NAME_PREFIX }}-${{ env.IMAGE_NAME_SUFFIX }}" }}:latest
           flavor:
             latest=false
           tags: |
@@ -121,13 +95,13 @@ jobs:
             type=raw,value=latest,enable={{ "{{is_default_branch}}" }}
 
       - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
+        uses: docker/setup-qemu-action@v3
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+        uses: docker/setup-buildx-action@v3
 
       - name: Login to Container Registry
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           {%- if cookiecutter.container_registry == 'Docker Hub' %}
           username: {{"${{ secrets.DOCKERHUB_USERNAME }}"}}
@@ -140,7 +114,7 @@ jobs:
           {%- endif %}
 
       - name: Build and push
-        uses: docker/build-push-action@v3
+        uses: docker/build-push-action@v4
         with:
           platforms: linux/amd64
           context: frontend/
